### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Fedjmike** [Fedjmike/Gosh#1]
I made this name up on the spot when I was filling in an (unsuccessful) application for Google Summer of Code. I'm not particularly attached to it so if I get something better I'll change it.
- Gosh (I like that it sounds like an exclamation of its own greatness)
- Tush, the typed [unix] shell (tush.io is free)
- Other words that end in "sh"
- Other words that _don't_ end in "sh"

It would be good if the name had a relevant domain available. [instantdomainsearch.com](https://instantdomainsearch.com/)

I will note that I like how Mercurial's executable is called Hg, so longer names are also reasonable.

**Comment by satyarth** [comment]
:+1: for tush

**Comment by nbrick** [comment]
I also like tush. (tush or Tush?)

Other ideas:
- funsh (functional shell (and fun!))
- xel (/ʒɛl/  - the x is the same sound as s in plea**s**ure)

**Comment by Fedjmike** [comment]
Tush is growing on me so for now I've renamed the repo and updated the website.

**Comment by Fedjmike** [comment]
With 1c871bbff684c1ca891b52be7b36ca0b4b3095bd, I now consider this closed.
