### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by dario23** [Fedjmike/Gosh#3]
git revision d2fb2f186142a739faec237d32589c3d8a51f7bb doesn't build for me

i cloned tush and libkiss, have debian libgc-dev and libreadline-dev installed.

the build doesn't seem to find putnchar (and grep doesn't either), so this is failing to build here.

> make
> src/ast-printer.c:15:5: error: implicit declaration of function 'putnchar' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>     putnchar(' ', ctx->depth_2 + 1);
>     ^
> src/ast-printer.c:15:5: note: did you mean 'putchar'?
> /usr/include/stdio.h:580:12: note: 'putchar' declared here
> extern int putchar (int __c);
>            ^
> src/ast-printer.c:24:5: error: implicit declaration of function 'for_vector' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>     for_vector (ast_ child, node->children, {
>     ^
> src/ast-printer.c:24:17: error: unexpected type name 'ast': expected expression
>     for_vector (ast\* child, node->children, {
>                 ^
> src/ast-printer.c:24:22: error: use of undeclared identifier 'child'
>     for_vector (ast\* child, node->children, {
>                      ^
> src/ast-printer.c:24:45: error: expected expression
>     for_vector (ast\* child, node->children, {
>                                             ^
> src/ast-printer.c:23:40: error: unused parameter 'ctx' [-Werror,-Wunused-parameter]
> static void printChildren (printerCtx\* ctx, const ast\* node) {
>                                        ^
> 6 errors generated.
> Makefile:14: recipe for target 'obj/ast-printer.o' failed
> make: **\* [obj/ast-printer.o] Error 1

**Comment by Fedjmike** [comment]
Thanks for trying to build it!

I've been lazy regarding updating the libkiss repo and generally making it easy for others to build. I've now gone through and committed various things that had only been in my working tree.

It should compile now if you pull both repos. You will first need to `make` in the libkiss directory. Note that it assumes the libkiss and tush repos are siblings in the same directory (tush looks for `../libkiss/libkiss.a`).

Out of interest, what is your `uname -a`? I'd be interested to know if it can compile on other Unices.

**Comment by Fedjmike** [comment]
I've got continuous integration set up now, so I'll mark this issue closed.

https://travis-ci.org/Fedjmike/tush

**Comment by dario23** [comment]
```
$ uname -a
Linux notbuch 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```

and builds fine now, thanks :-)
